//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnikeyFactoryTest.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestPlatformDBEntities : DbContext
    {
        public TestPlatformDBEntities()
            : base("name=TestPlatformDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdministratedAnswer> AdministratedAnswers { get; set; }
        public virtual DbSet<AdministratedQuestion> AdministratedQuestions { get; set; }
        public virtual DbSet<AdministratedTest> AdministratedTests { get; set; }
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<User> Users { get; set; }

        public System.Data.Entity.DbSet<UnikeyFactoryTest.Presentation.Models.DTO.AdministratedTestDto> AdministratedTestDtoes { get; set; }
    }
}
